main:
  - name: People
    url: people/
    weight: 10
  - name: Projects
    url: project/
    weight: 20
  - name: Publications
    url: publication/
    weight: 30
  - name: News
    url: post/
    weight: 40
  - name: Gallery
    url: gallery/
    weight: 50
  - name: SFB @UCF
    url: sfb/
    weight: 55
  - name: Contact
    url: contact/
    weight: 60

